config/routes.rb
Rails.application.routes.draw do

  get '(errors)/:status' => 'errors#show', constraints: { status: /\d{3}/ }, via: :all

  devise_for :users, skip: [:sessions, :passwords, :registrations]

  #scope '(:locale)' do

  #scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    root 'static_pages#home'

    #get '/:project_name' => 'projects#show', constraints: { id: /\d.+/ }, as: 'proj_id'


    #get '/:id' => 'projects#show', id: /login\/[^\/]+/
    get '/about' => 'static_pages#about', as: 'about'
    as :user do
      # session handling
      get     '/login'  => 'devise/sessions#new',     as: 'new_user_session'
      post    '/login'  => 'devise/sessions#create',  as: 'user_session'
      delete  '/logout' => 'devise/sessions#destroy', as: 'destroy_user_session'

      # joining
      get   '/join'    => 'devise/registrations#new',       as: 'new_user_registration'
      post  '/join'    => 'users/registrations#create',    as: 'user_registration'
      put   '/join'    => 'users/registrations#update',  as: ''
      # account deletion
      delete '/join' => 'devise/registrations#destroy', as: ''

      # password reset
      get   '/reset_password'        => 'devise/passwords#new',    as: 'new_user_password'
      post  '/reset_password'        => 'users/passwords#create', as: 'user_password'
      get   '/password/change'       => 'devise/passwords#edit',   as: 'edit_user_password'
      put   '/reset_password'        => 'devise/passwords#update', as: ''


      scope '/settings' do

        # confirmation
        # get   '/confirm'        => 'devise/confirmations#show',   as: 'person_confirmation'
        # post  '/confirm'        => 'devise/confirmations#create'
        # get   '/confirm/resend' => 'devise/confirmations#new',    as: 'new_user_confirmation'

        # settings & cancellation
        get '/cancel'  => 'devise/registrations#cancel',  as: 'cancel_user_registration'
        get '/profile' => 'users/registrations#edit',    as: 'edit_user_registration'
      end
    end

    resources :projects, path: '', except: [ :index, :create ] do
      resources :items, only: [ :index, :create, :destroy, :update ], on: :member do
        resources :track_items, only: [ :create, :update, :destroy ]
      end
      collection do
        get 'new' => 'projects#new', as: 'projects_path'
        post 'new' => 'projects#create'
      end
      post 'more_info' => 'project#more_info', as: 'more_info', on: :member
    end
  #end

  post 'set_locale' => 'sessions#set_locale', as: 'set_locale'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  include ApplicationHelper
  include ProjectsHelper
  before_action :no_header_footer!, only: [ :home ]
  before_action :set_projects, only: [ :home ]
  
  def home
    
  end

  def help
  end

  def about
  end

  def contact
  end
  
private
  def set_projects
    @projects = current_user.projects if current_user.present?
  end
end

app/views/static_pages/_no_signed.html.haml
#site-container.context-loader-container{"data-pjax-container" => ""}
  .marketing-section.marketing-section-signup
    .container
      = form_for(:user, url: user_registration_path, html: { class: "form-signup-home" }) do |f|
        %dl.form
          %dd
            = f.text_field :name, autofocus: true, placeholder: 'Your name'
        %dl.form
          %dd
            = f.email_field :email, placeholder: 'Your email'
        %dl.form
          %dd
            = f.password_field :password, autocomplete: "off", placeholder: 'Create a password'
        %dl.form
          %dd
            = f.password_field :password_confirmation, autocomplete: "off", placeholder: 'Confirm password'
        = f.button "Sign up", class: 'button primary button-block'
      %h1.heading Watch the performance.

/ .covervid-wrapper
/   = video_tag(['clouds.webm'], autoplay: true, loop: true, class: "covervid-video")

app/views/static_pages/_signed.html.haml
%section{style: "background: #DDDDDD;"}
  %header.bck.dark.custom-header-tuk
    %h4.on-left.text.thin{style: "margin-left: 50px;"}
      .add-project
        = link_to new_project_path, class: "" do
          = fa_icon "plus", text: "New project" 
          %span.badge= @projects.count
    = form_tag("", method: "get", class: "on-left signed-search") do
      = text_field_tag :q, '', placeholder: "Search", autocapitalize: "off"
    %nav.on-right{style: "margin-right: 50px;"}
      .user-signed
        .dropdown
          = link_to edit_user_registration_path, class: 'settings-link dropdown-toggle', data: {toggle: :dropdown} do
            = gravatar_for current_user, size: 40
            %span.name= current_user.name || current_user.email
            %span.caret
            %ul{ class: 'dropdown-menu m-menu', role: 'menu'}
              %li= link_to "Settings", edit_user_registration_path, class: "settings"
              %li.divider
              %li= link_to "Logout", destroy_user_session_path, method: "delete", class: "logout"

  %article.padding.scroll
    .margin-bottom
      %h4.text.book.inline
        %span.icon.star.color.dark
        Projects
    .inline.project-list
      - @projects.newer.each do |project|
        .project-box
          = link_to project_path(project), data: { confirm: "Are you sure you want to do this?" }, method: :delete, class: "button danger custom-delete" do
            = fa_icon "times"
          #project.ho-box.project{data: {content: "#project-content_#{project.id}", url: "#{project_url(project)}"}} 
            - if project.image.present?
              = image_tag project.image, style: "width:320px; height:200px;"
            - else
              %div{style: "width: 320px; height: 200px; position: relative;"}
                = fa_icon "camera-retro", class: "project-icon project-image"
          #project-content.ho-content{id: "#{project.id}"}
            .hover-content-block
              %strong.name= fl(project.name)
              %p= project.description
              .p-items Items: #{project.items.count}
              .p-track-items Track items: #{project.track_items.count}
              %br
              - if project.track_items.present?
                .p-last Last activity: #{activity_time(PublicActivity::Activity.where(owner: project, owner_type: "Project").last, type: :short) }
              .p-created Created: #{project.created_at}
               

:css
  [data-tuktuk=boxes]{display:-moz-box;}
  [data-tuktuk=boxes] > aside,[data-tuktuk=boxes] > section{display:-moz-box;}
  [data-tuktuk=buttons]{display:-moz-box;}
  [data-tuktuk=totals]{display:-moz-box;}
  [data-tuktuk="modal"].side > div{display:-moz-box;}
  [data-tuktuk="modal"].side{display:-moz-box;}
  .flexbox { display:-moz-box;}
  [data-tuktuk=boxes] > aside > div{display:-moz-box;}

app/views/static_pages/about.html.haml
- provide(:title, 'About Us')

%h1 About Us
%p
  It's a new history

app/views/static_pages/contact.html.haml
- provide(:title, 'Contact')
%h1 Contact
%p
  Contact with otec.

app/views/static_pages/help.html.haml
- provide(:title, 'Help')
%h1 Help
%p
  Get help

app/views/static_pages/home.html.haml
- if signed_in?
  = render 'signed'
- else
  = render 'no_signed'
    















/ - if user_signed_in?
/   %span Здравствуйте, #{current_user.email}
/   = link_to 'Выйти', destroy_user_session_path, method: :delete
/ - else 
/   = link_to 'Войти', new_user_session_path 
/   или 
/   = link_to 'Зарегистрироваться', new_user_registration_path

/ %div
/   %h1 Welcome to the Body-Stats
/   %h2 This is the home page.