config/routes.rb
Rails.application.routes.draw do

  get '(errors)/:status' => 'errors#show', constraints: { status: /\d{3}/ }, via: :all

  devise_for :users, skip: [:sessions, :passwords, :registrations]

  #scope '(:locale)' do

  #scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    root 'static_pages#home'

    #get '/:project_name' => 'projects#show', constraints: { id: /\d.+/ }, as: 'proj_id'


    #get '/:id' => 'projects#show', id: /login\/[^\/]+/
    get '/about' => 'static_pages#about', as: 'about'
    as :user do
      # session handling
      get     '/login'  => 'devise/sessions#new',     as: 'new_user_session'
      post    '/login'  => 'devise/sessions#create',  as: 'user_session'
      delete  '/logout' => 'devise/sessions#destroy', as: 'destroy_user_session'

      # joining
      get   '/join'    => 'devise/registrations#new',       as: 'new_user_registration'
      post  '/join'    => 'users/registrations#create',    as: 'user_registration'
      put   '/join'    => 'users/registrations#update',  as: ''
      # account deletion
      delete '/join' => 'devise/registrations#destroy', as: ''

      # password reset
      get   '/reset_password'        => 'devise/passwords#new',    as: 'new_user_password'
      post  '/reset_password'        => 'users/passwords#create', as: 'user_password'
      get   '/password/change'       => 'devise/passwords#edit',   as: 'edit_user_password'
      put   '/reset_password'        => 'devise/passwords#update', as: ''


      scope '/settings' do

        # confirmation
        # get   '/confirm'        => 'devise/confirmations#show',   as: 'person_confirmation'
        # post  '/confirm'        => 'devise/confirmations#create'
        # get   '/confirm/resend' => 'devise/confirmations#new',    as: 'new_user_confirmation'

        # settings & cancellation
        get '/cancel'  => 'devise/registrations#cancel',  as: 'cancel_user_registration'
        get '/profile' => 'users/registrations#edit',    as: 'edit_user_registration'
      end
    end

    resources :projects, path: '', except: [ :index, :create ] do
      resources :items, only: [ :index, :create, :destroy, :update ], on: :member do
        resources :track_items, only: [ :create, :update, :destroy ]
      end
      collection do
        get 'new' => 'projects#new', as: 'projects_path'
        post 'new' => 'projects#create'
      end
      post 'more_info' => 'project#more_info', as: 'more_info', on: :member
    end
  #end

  post 'set_locale' => 'sessions#set_locale', as: 'set_locale'
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  extend Babosa
  
  before_save { self.name = name.mb_chars.downcase }
  friendly_id :name, use: [ :scoped, :slugged, :finders ], scope: :user
  
  belongs_to :user
  has_many :items, dependent: :destroy
  
  scope :newer, -> { order("created_at ASC") }

  validates :name, presence: true, length: { maximum: 30 }#, uniqueness: { scope: :user_id, case_sensitive: false } тоже самое что и метод
  validate :uniq_proj_for_user

  validates :description, presence: true, length: { maximum: 50 }

  mount_uploader :image, ImageUploader

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :russian).to_s
  end
  
  def should_generate_new_friendly_id?
    name_changed?
  end

  def uniq_proj_for_user
    if Project.exists? ["user_id = ? AND (name = ? OR slug = ?)", 
                          user_id, 
                          name.mb_chars.downcase, 
                          normalize_friendly_id(name.mb_chars.downcase)
                        ]
      errors.add( :name, 'project already exists on this account' )
    end
  end

  def track_items
    items = TrackItem.joins(item: :project).where(items: { project_id: id })
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ApplicationHelper
  include ProjectsHelper
  before_action :authenticate_user!
  before_action :set_project, only: %w{show edit update destroy more_info}
  before_action :no_header_footer!, only: [ :show ]
  before_action :units, only: [ :show ]
  before_action ->(type=params[:type], count=params[:count]) { more_info_details(type, count) }, only: [ :show ]
  
  def new
    @project = Project.new
  end
  
  def show
    @activities = get_activities
    @last = last_track_item @activities
    @report = report(@project.track_items.send(session[:type], session[:count]))
    
    #raise InternalServerError, "Its 500 Error" # test 500 error 
    
    #gon.hide_right_block = true if @project.items.empty?
    # "DAYOFMONTH(created_at) = ? or MONTH(created_at) = ?"
    # data = Net::HTTP.get(URI.parse("http://www.highcharts.com/samples/data/jsonp.php?filename=aapl-c.json&callback=?"))
  end 
  
  def create
    @project = current_user.projects.build(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to project_items_url(@project) }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update_attribute(:image, project_params[:image])
        format.html { redirect_to @project }
        format.js {}
      else
        format.html { redirect_to @project }
      end
    end
  end
  
  def destroy
    @project.destroy
    redirect_to root_url
  end
    
  private 

    def more_info_details(type, count)
      set_more_info(type, count)
    end

    def set_project
      @project = current_user.projects.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :description, :image)
    end
    
    
end

app/helpers/projects_helper.rb
module ProjectsHelper
  
  def render_chart(project)
    LazyHighCharts::HighChart.new('stock') do |f|
      f.rangeSelector(selected: 1, inputEnabled: true,
                      buttons: [{type: 'day',count: 1,text: '1D'}, 
                                {type: 'week',count: 1,text: '1W'}, 
                                {type: 'month',count: 1,text: '1M'},  
                                {type: 'month',count: 6,text: '6M'}, 
                                {type: 'year',count: 1,text: '1Y'}, 
                                {type: 'all',count: 1,text: 'All'}])
      project.items.includes(:track_items).each do |i|  
        data = i.track_items.map {|tr| [tr.created_at.to_i * 1000, tr.user_data] }
        visible = i != project.items[0] ? false : true
        f.series(name: i.name, 
                  data: data,
                  tooltip: { valueDecimals: 2},
                  marker: { enabled: true, radius: 3},
                  visible: visible,
                  shadow: true)
      end
      f.legend(enabled: true)
      f.plotOptions(spline: { turboThreshold: 2000}, line: { dataLabels: { enabled: true }})
      f.credits(enabled: false)
    end
  end

  def get_activities(project=@project)
    PublicActivity::Activity.includes([
      {trackable: {item: {project: :user}}}, {owner: :user}, :trackable
    ]).order("created_at desc").where(owner: project, owner_type: "Project").limit(20)
  end

  def last_track_item(activities)
    activities.map(&:trackable).compact[0]
  end

  def report(project_track_items)
    sorted_tr = []
    @project.items.each do |item|
      sorted_tr[item.id] = {item_id: item.id, item_name: item.name, unit: unit(item.unit_id),start_user_data: '', end_user_data: '', data_count: 0}
      project_track_items.each do |ptr|
        if ptr.item_id == item.id
          sorted_tr[item.id][:data_count] += 1
          if sorted_tr[item.id][:start_date] && sorted_tr[item.id][:end_date]
            if sorted_tr[item.id][:start_date] > ptr.created_at
              sorted_tr[item.id][:start_user_data] = ptr.user_data
              sorted_tr[item.id][:start_date] = ptr.created_at
            elsif sorted_tr[item.id][:end_date] < ptr.created_at
              sorted_tr[item.id][:end_user_data] = ptr.user_data
              sorted_tr[item.id][:end_date] = ptr.created_at
            end
          else
            sorted_tr[item.id][:start_user_data] = ptr.user_data
            sorted_tr[item.id][:end_user_data] = ptr.user_data
            sorted_tr[item.id][:start_date] = ptr.created_at
            sorted_tr[item.id][:end_date] = ptr.created_at
          end
        end
      end
    end
    sorted_tr.compact
  end

end

app/views/projects/_activities.html.haml
- @activities.each do |activity|
  = render_activity activity, layout: "layouts/activity_wrapper"
  %hr/

app/views/projects/_latest_activity.html.haml
- unless @last.nil?  
  .time= activity_time(@last, type: :short)
  %abbr.owner= @last.item.project.user.name
  added
  %abbr.user-data
    = @last.user_data 
    = unit(@last.item.unit_id)
  to 
  %abbr.item-name= fl(@last.item.name)
- else
  No activity
    

app/views/projects/_menu_links.html.haml
= link_to root_path, class: 'active' do
  %span.icon.star
  Projects
  %small (#{current_user.projects.count})
= link_to project_items_url(@project) do
  = fa_icon "bars", text: "Items", class: "icon"
  %small (#{@project.items.count})
= link_to '#', data: {"tuktuk-box" => "menu"} do
  = fa_icon "bar-chart-o", text: "Track Items", class: "icon"
  %small (#{@project.track_items.count})
= link_to '#' do
  = fa_icon "image", text: "Images", class: "icon"
  %small (55)

app/views/projects/_more_info.html.haml
- @report.each do |r|
  .mas.bck.light.margin-bottom
    %h2.i-name= fl(r[:item_name])
    - if r[:start_user_data].present? && r[:end_user_data].present?
      %h1.u-percent
        - perc = percent(r[:start_user_data], r[:end_user_data])
        - if perc > 0
          .prog= "+#{perc.to_s(:percentage, precision: 2)}"
        - elsif perc == 0
          .nopr= "+#{perc.to_s(:percentage, precision: 2)}"
        - else
          .degr= perc.to_s(:percentage, precision: 2)
      .u-data-start
        = fa_icon "chevron-down", text: "#{r[:start_user_data]} #{r[:unit]}", class: "icon"
      .date= r[:start_date].strftime("%B %e, %Y")
      .clearfix
      .u-data-end
        = fa_icon "chevron-up", text: "#{r[:end_user_data]} #{r[:unit]}", class: "icon"
      .date= r[:end_date].strftime("%B %e, %Y") 
      .clearfix
      .d-count Number of data: #{r[:data_count]}
    - else
      .no-data No data

app/views/projects/_project_image.html.haml
= simple_form_for(@project, html: {class: "project-image-form"}, remote: true) do |f|
  = f.input :image, label: false
- if @project.image.url.present?
  = image_tag(@project.image.url.to_s, title:"Click to change image", class: "responsive project-image")
- else
  %div{style: "width: 247px; height: 155px; position: relative;"}
    = fa_icon "camera-retro", class: "project-icon project-image"

app/views/projects/_stock_chart.html.haml
= link_to 'labels', '#', data:{ tip:"Click to on/off data labels"}, class: "toggle-labels btn custom-button-dark chart-butt"
= link_to 'markers', '#', data:{ tip:"Click to on/off data markers"}, class: "toggle-markers btn custom-button-dark chart-butt"
= link_to 'line', '#', data:{ tip:"Click to view line chart"}, class: "toggle-line btn custom-button-dark chart-butt"
= link_to 'spline', '#', data:{ tip:"Click to view spline chart"}, class: "toggle-spline btn custom-button-dark chart-butt"
= link_to 'areaspline', '#', data:{ tip:"Click to view areaspline chart"}, class: "toggle-areaspline btn custom-button-dark chart-butt"
= link_to 'area', '#', data:{ tip:"Click to view area chart"}, class: "toggle-area btn custom-button-dark chart-butt"
= link_to 'column', '#', data:{ tip:"Click to view column chart"}, class: "toggle-column btn custom-button-dark chart-butt"

= high_stock('project_stock', render_chart(@project)) 

app/views/projects/new.html.haml
.new-repo-container
  = simple_form_for(@project) do |f|
    %h1 Create Your Own Project
    .with-permission-fields
      %p 
        Great project names are short and memorable. Need inspiration? How about
        %strong otec
      %dl.form
        %dd= f.input :name, label: "Project Name", input_html: { class: "long" }, required: false, autofocus: true, placeholder: "Name of the monitored project"
      %dl.form
        %dd= f.input :description, label: "Description", required: false, autofocus: true, placeholder: "Optional", input_html: { class: "long" }
      %hr
      = f.button :submit, "Create project", class: "button primary first-in-line"

app/views/projects/show.html.haml
%aside#menu.absolute.bck.light.column_5
  %header.bck.light
    .session.on-left
      %strong
        Project Activities
    %a.on-right.text.big.icon.remove.color.white{"data-box" => "close", :href => "#"}
  %article.bck.dark.scroll
    .margin.activities
      = render 'activities'
      
%aside.column_3.aside-left
  %header.bck.light
    .session.on-left
      %strong
        logged in as
        = link_to current_user.name, edit_user_registration_path, class: "color theme"
    = link_to '', edit_user_registration_path, class: "on-right text big icon cog"
  %article.bck.light.scroll
    .project-image-block
      = render 'project_image'
    .margin-left.margin-right
      %h4.text.bold.color.theme.inline= current_user.name
      %span.margin-left.tag.bck.color.inline.text.bold owner
      .block
        %span.icon.user
        = current_user.email
    %hr/
    .margin
      %strong.text.big.normal.block= fl(@project.name)
      .display.block.text.justify.small= @project.description
    %hr/
    %nav.text.bold.menu-links{data:{tuktuk:"menu"}}
      = render "menu_links"
    %hr/
    .margin
      %strong.text.big.normal.block 
        %span.glyphicon.glyphicon-bell 
        Latest Activity
      .margin
        .latest-activity
          = render 'latest_activity'
      .margin
        %button.btn.custom-button-dark{"data-tip" => "Click to view a all activities", "data-tuktuk-box"=>"menu"} More Activities
%section
  %header.bck.dark.custom-header-tuk
    %h3.on-left.text.thin
      = link_to fl(@project.name), project_path(@project)
      %span.tag.bck.theme Project
    %nav.on-right
      = @project.description
  %article.scroll.padding
    - if @project.items.present?  
      .margin-bottom
        %h4.text.book.inline
          %span.icon.list-alt.color.theme
          .chart-toggle{style: "display: inline-block"} Chart data
      .inline.my-stock-chart
        = render 'stock_chart'
      .margin-bottom
        %h4.text.book.inline
          %span.icon.list.color.theme
          .details-toggle{style: "display: inline-block"} More details
          %form{action: project_path(@project), data: {remote: true}, method: :get, "accept-charset" => "UTF-8", class: "detail-form"}
            = select_tag :type, options_for_select(TrackItem::SCOPE_TYPES),  prompt: false, class: "type form-control"
            = text_field_tag(:count, 1, class: "count")
            = submit_tag 'Go', name: nil, class: "go"
      .inline.info-hide-block{style: "width: 100%;"}
        .more-info
          = render 'more_info'

    - else
      .margin
        %h1 CREATE YOUR PROJECT DATA
  %footer.bck.dark{style: "padding: 0; margin: 0"}
    = link_to '', '#', class: "glyphicon glyphicon-chevron-left on-left bck dark b-hide b-left"
    = link_to '', '#', class: "glyphicon glyphicon-chevron-right on-right bck dark hid b-hide b-right"
    %nav.on-left.text.bold{"data-tuktuk" => "menu", style: "margin-left: 50px"}
      = link_to '#', class: "active" do
        Projects
        %small (9)
      = link_to '#' do
        Items
        %small (9)
      = link_to '#' do
        Track Items
        %small (192)
      = link_to '#' do
        Images
        %small (55)

%aside.column_3.aside-right{style: "float: right"}
  %header.bck.light
    = link_to '', project_items_path(@project), class: "on-right text big icon cog"
    %h4.inline.text.book Enter your data
  %article.form.scroll
    - unless @project.items.empty?
      %div.track-items-table
        - @project.items.each do |item|
          %div.track-cont
            = simple_form_for([@project, item, item.track_items.build], remote: true) do |f|
              %dl.form.track
                %dd.dib= f.input :user_data, label: fl(item.name), placeholder: "enter", autofocus: true, required: false, input_html: {step: 0.1}
                %dd.dib= unit(item.unit_id)
    - else
      %h1{style: "text-align:center; padding-top: 15px;"} #{link_to 'Add project items', project_items_path(@project)}

:css
  body { overflow: hidden; }
  [data-tuktuk=boxes]{display:-moz-box;}
  [data-tuktuk=boxes] > aside,[data-tuktuk=boxes] > section{display:-moz-box;}
  [data-tuktuk=buttons]{display:-moz-box;}
  [data-tuktuk=totals]{display:-moz-box;}
  [data-tuktuk="modal"].side > div{display:-moz-box;}
  [data-tuktuk="modal"].side{display:-moz-box;}
  .flexbox { display:-moz-box;}
  [data-tuktuk=boxes] > aside > div{display:-moz-box;}

  