config/routes.rb
Rails.application.routes.draw do

  get '(errors)/:status' => 'errors#show', constraints: { status: /\d{3}/ }, via: :all

  devise_for :users, skip: [:sessions, :passwords, :registrations]

  #scope '(:locale)' do

  #scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    root 'static_pages#home'

    #get '/:project_name' => 'projects#show', constraints: { id: /\d.+/ }, as: 'proj_id'


    #get '/:id' => 'projects#show', id: /login\/[^\/]+/
    get '/about' => 'static_pages#about', as: 'about'
    as :user do
      # session handling
      get     '/login'  => 'devise/sessions#new',     as: 'new_user_session'
      post    '/login'  => 'devise/sessions#create',  as: 'user_session'
      delete  '/logout' => 'devise/sessions#destroy', as: 'destroy_user_session'

      # joining
      get   '/join'    => 'devise/registrations#new',       as: 'new_user_registration'
      post  '/join'    => 'users/registrations#create',    as: 'user_registration'
      put   '/join'    => 'users/registrations#update',  as: ''
      # account deletion
      delete '/join' => 'devise/registrations#destroy', as: ''

      # password reset
      get   '/reset_password'        => 'devise/passwords#new',    as: 'new_user_password'
      post  '/reset_password'        => 'users/passwords#create', as: 'user_password'
      get   '/password/change'       => 'devise/passwords#edit',   as: 'edit_user_password'
      put   '/reset_password'        => 'devise/passwords#update', as: ''


      scope '/settings' do

        # confirmation
        # get   '/confirm'        => 'devise/confirmations#show',   as: 'person_confirmation'
        # post  '/confirm'        => 'devise/confirmations#create'
        # get   '/confirm/resend' => 'devise/confirmations#new',    as: 'new_user_confirmation'

        # settings & cancellation
        get '/cancel'  => 'devise/registrations#cancel',  as: 'cancel_user_registration'
        get '/profile' => 'users/registrations#edit',    as: 'edit_user_registration'
      end
    end

    resources :projects, path: '', except: [ :index, :create ] do
      resources :items, only: [ :index, :create, :destroy, :update ], on: :member do
        resources :track_items, only: [ :create, :update, :destroy ]
      end
      collection do
        get 'new' => 'projects#new', as: 'projects_path'
        post 'new' => 'projects#create'
      end
      post 'more_info' => 'project#more_info', as: 'more_info', on: :member
    end
  #end

  post 'set_locale' => 'sessions#set_locale', as: 'set_locale'
end

app/views/layouts/_activity_wrapper.html.haml
.activity
  .body
    - unless p[:info][:track_item_id].nil?
      .mega-icon.item-id
        = "##{p[:info][:track_item_id]}"
    - else 
      .mega-icon{ style: "background-image: url(#{image_path "icons/#{a.key}.svg"}); width: 30px; height: 30px;"}
    %abbr.timeago= activity_time(a)
    .title
      = link_to a.owner.user.name || a.owner.user.email, edit_user_registration_path if a.owner
      = content_for :action
      .details
        .avatar
          = gravatar_for(a.owner.user, size: 35)
        .message
          = yield

app/views/layouts/_footer.html.haml
.container.footer
  .site-footer
    %ul.site-footer-links.right
      %li= link_to 'Status', '#'
      %li= link_to 'API', '#'
      %li= link_to 'Training', '#'
      %li= link_to 'Shop', '#'
      %li= link_to 'Blog', '#'
      %li= link_to 'About', about_path
      / = form_tag  set_locale_path, class: 'locale' do
      /   = select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()'
      /   = submit_tag 'submit'
      /   = javascript_tag "$('.locale input').hide()"
    %ul.site-footer-links
      %li
        © 2014
        %span Performance
      %li= link_to 'Terms', '#'
      %li= link_to 'Privacy', '#'
      %li= link_to 'Security', '#'
      %li= link_to 'Contact', '#'

app/views/layouts/_header.html.haml
.header.custom-header
  .container.clearfix
    = link_to root_path, class: 'header-logo-wordmark' do
      %span.mega-octicon Performance
    .header-actions
      - if signed_in?
        %span#user-links
          = link_to edit_user_registration_path, class: 'name' do
            = gravatar_for current_user, size: 20
            = current_user.name || current_user.email
        = link_to 'Logout', destroy_user_session_path, method: :delete, class: "button"
      - else
        = link_to 'Sign up', new_user_registration_path, class: "button primary"
        = link_to 'Sign in', new_user_session_path,  class: "button signin"
    .command-bar
      / %ul.top-nav
      /   %li.explore
      /     %a{href: "#"} Explore
      /   %li.features
      /     %a{href: "#"} Features
      /   %li.enterprise
      /     %a{href: "#"} Enterprise
      /   %li.blog
      /     %a{href: "#"} Blog
      = form_tag("/search", method: "get", class: "command-bar-form", id: "top_search_form") do
        .commandbar
          %span
          = text_field_tag :q, '',  id: "js-command-bar-field", tabindex: "1", placeholder: "Search", autocapitalize: "off", "data-hotkey" => "s"
.custom-header-fix

app/views/layouts/_shim.html.haml
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title yield :title
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = render 'layouts/shim'
  %body{ data: { tuktuk: @tuktuk } }
    = include_gon
    = render :partial => "shared/frontend_notifier"
    = my render('layouts/header')
    = yield
    = my render('layouts/footer')
    / нужно что бы скрипт был подключен в конце документа
    = javascript_include_tag 'tuktuk/tuktuk', 'data-turbolinks-track' => true